name: Build

on:
  push:

jobs:
#  golangci-lint:
#    name: lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          working-directory: app
#          args: --skip-files api.go
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Test
        run: go test ./... -race

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v2

      - name: Update SSL certificated
        run: |
          sudo update-ca-certificates

      - uses: extractions/setup-just@v1

      - uses: docker/setup-buildx-action@v2

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: "projects/28860527365/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: deploy@tf2pickup-ratings.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build
        run: just build

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: europe-west3-docker.pkg.dev/tf2pickup-ratings/tf2pickup-ratings/pickup-ratings:latest
          provenance: false
